version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of the package.json file
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "react-scripts"
        versions: ["5.0.1"]
